name: Waka Readme

on:
  schedule:
    # Executa todos os dias às 00:00 UTC
    - cron: '0 */12 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.WAKA_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_LINES_OF_CODE: "True"   # Ativa a exibição do total de linhas de código
          SHOW_PROFILE_VIEWS: "False"  # Desativa a contagem de visualizações do perfil
          # Adicione ou modifique outras flags conforme sua preferência
